name: Build and Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js and install dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # Step 3: Build the project
      - name: Build project
        run: npm run build
        
      # Step 4: Push the build to a separate branch (e.g., `deploy`)
      # - name: Push Build
      #   run: |
      #     git config --local user.name "GitHub Actions"
      #     git config --local user.email "actions@github.com"
      #     git add dist
      #     git commit -m "Deploy production build"
      #     git push origin +HEAD:build
      - name: Push build
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: dist
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          MESSAGE: "Build ({sha}) {msg}" # Commit message
